### PR TITLE
axum 0.8

### PR DESCRIPTION
**Pull request by yanns**
https://github.com/tokio-rs/axum/releases/tag/axum-v0.8.0-alpha.1

### CODE REVIEW

**Comment by Ptrskay3** [comment]
Thanks!

I think because of the `matchit` update, we'll need to update that too, and the examples need to be migrated as well.

**Comment by yanns** [comment]
I've updated the examples.
but I don't have the behavior described in https://github.com/Ptrskay3/axum-prometheus/pull/69/files#diff-be18049a2d956c1591258fcd5925b4178b6f9d1b09aa4ad14a4ffbbd6f09409eR41

**Comment by yanns** [comment]
> > I've tested this change on an internal application, and the metrics are working well.
> > Some metrics values have changed to use the `{...}` convention instead of `:....` so that some dashboards must have been adapted. Something worth mentioning in release notes.
> 
> Cool, really appreciate the effort. What about your previous comment? Is it still behaving differently?

Yes, no change here.
But maybe it's also broken on `main`. Something I have to check.

**Comment by yanns** [comment]
I confirm that the application does not behave like it's described in the comment on the `main` branch.

Calling http://localhost:3000/baz/qux/2
creates the following entry:
```
axum_http_requests_total{method="GET",status="200",endpoint="/baz/qux/:a"} 1
```

and not
```
axum_http_requests_total{method="GET",status="200",endpoint="/baz/qux/2_changed"} 1
```
as described in the comment.

So the migration to axum 0.8 does not change this behavior.

**Comment by Ptrskay3** [comment]
Well, I created #72 for that bug.

Thanks for the PR. Probably I'll have time to test the changes this weekend, but looks good. 

Do you want to write the changelog as well, or should I?

**Comment by yanns** [comment]
> Do you want to write the changelog as well, or should I?

I added it: https://github.com/Ptrskay3/axum-prometheus/pull/69/commits/9de885d0f655e83c2b7cfb4c04d91bbeba779655

**Review by Ptrskay3 — APPROVED** [review]
Thanks again!

**Pull request merged**
