### PR TITLE
tests needs the 'util' feature of tower

### PR DESCRIPTION
**Pull request by yanns**

### CODE REVIEW

**Comment by Ptrskay3** [comment]
Maybe I'm missing something, but the tests were green before that change too?

**Comment by yanns** [comment]
> Maybe I'm missing something, but the tests were green before that change too?

for me, the tests do not compile:
```
error[E0432]: unresolved import `tower::ServiceExt`
   --> tests/prefix.rs:5:38
    |
5   | use tower::{Service, ServiceBuilder, ServiceExt};
    |                                      ^^^^^^^^^^
    |                                      |
    |                                      no `ServiceExt` in the root
    |                                      help: a similar name exists in the module: `Service`
    |
    = help: consider importing this trait instead:
            axum::ServiceExt
```

**Comment by Ptrskay3** [comment]
Just bumped `tower` and `tower_http` on master, and it worked for me :thinking: :
https://github.com/Ptrskay3/axum-prometheus/pull/71/checks

**Comment by yanns** [comment]
> Just bumped `tower` and `tower_http` on master, and it worked for me 🤔 : https://github.com/Ptrskay3/axum-prometheus/pull/71/checks

This is also working for me. Better merging https://github.com/Ptrskay3/axum-prometheus/pull/71 than this PR then.

**Pull request closed without merging**
